services:
  # Static Site Deployment on Render
  - type: web
    name: praveen-portfolio
    env: node
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=31536000, immutable
